# docker-compose.yml (LOKÁLIS SQLite fejlesztéshez)
# Ezt NEM használja az OpenShift!
version: '3.8' # Ez a sor már nem kötelező

services:
  web:
    build: .
    # Helyi fejlesztéshez maradhat a runserver
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # Kód szinkronizálása
      # Az SQLite fájl és a médiafájlok a konténeren belül jönnek létre (és a volume mount miatt a hoston is)
      # Nincs szükség külön volume-ra lokálisan, ha a .: /app mount megvan
    ports:
      - "8000:8000"
    env_file:
      - ./.env # Lokális .env használata