# docker-compose.yml (LOKÁLIS SQLite fejlesztéshez)
services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn photoalbum.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media 
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db: 
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres_data: # Adatbázis volume
  static_volume: # Statikus fájlok volume
  media_volume: # Médiafájlok volume