# Generated by Django 5.2 on 2025-04-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Név')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Képfájl')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltés dátuma')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'photos',
                'ordering': ['-upload_date'],
            },
        ),
    ]
