# Generated by Django 5.2 on 2025-05-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='processed_s3_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
